name: PR Metadata Validator
on:
  pull_request:
    types: [ opened, edited, reopened, milestoned, demilestoned ]

concurrency:
  group: ${{ github.event_name }}-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  convention-check:
    name: Validate PR Metadata
    uses: PrestaShop/.github/.github/workflows/validate-pr-metadata.yml@master
